version: 2
jobs:
  test:
    docker:
      - image: circleci/android:api-29
    steps:
      - run:
          name: Build debug APK
          command: |
            ./gradlew :app:assembleDebug
      - store_artifacts:
          path: \app\
          destination: app-debug
